export const LIST_NUMBER_ITEM_PER_PAGE_PRODUCT = [10, 25, 50, 75, 100]

export const STOCK_STATUS_OPTIONS = [
  { label: 'Any stock status', value: 'all' },
  { label: 'In stock', value: 'in' },
  { label: 'Low stock', value: 'low' },
  { label: 'SOLD', value: 'out' },
]

export const AVAILABILITY_OPTIONS = [
  { label: 'Any availability status', value: 'all' },
  { label: 'Only enabled', value: '1' },
  { label: 'Only disabled', value: '0' },
]

//  CHECK BOX SEARCH TYPE
export const SEARCH_TYPE_OPTIONS = [
  { label: 'Name', name: 'name' },
  { label: 'Sku', name: 'sku' },
  { label: 'Full description', name: 'description' },
]

export const CONDITION_OPTIONS = [{ label: 'Used', value: '292' }]

export const MEMBERSHIP_OPTIONS = [
  {
    label: 'General',
    value: '4',
  },
]

export const SALE_PRICE_TYPE_OPTIONS = [
  {
    label: '$',
    value: '$',
  },
  {
    label: '%',
    value: '%',
  },
]

export const OG_TAGS_TYPE_OPTIONS = [
  {
    label: 'Autogenerated',
    value: '0',
  },
  {
    label: 'Custom',
    value: '1',
  },
]

export const META_DESC_TYPE_OPTIONS = [
  {
    label: 'Autogenerated',
    value: 'A',
  },
  {
    label: 'Custom',
    value: 'C',
  },
]

export const STATUS_ACTION = {
  CREATE: 'create',
  UPDATE: 'update',
}
